// Generated by NAAb
use std::io::{Read, Write};
use std::os::unix::net::UnixListener;
use std::fs;
fn main() {
    let sock = "/data/data/com.termux/files/usr/tmp/passage_shield.sock";
    let _ = fs::remove_file(sock);
    let listener = UnixListener::bind(sock).unwrap();
    for stream in listener.incoming() {
        if let Ok(mut s) = stream {
            let mut buf = String::new();
            if let Ok(_) = s.read_to_string(&mut buf) {
                s.write_all(b"[]").unwrap();
            }
        }
    }
}
